
services:
  - type: web
    plan: free
    runtime: docker
    name: n8n-service
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_LISTEN_ADDRESS
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "https"
      - key: DB_TYPE
        value: "sqlite"
      - key: GENERIC_TIMEZONE
        value: "Africa/Nouakchott"
      - key: TZ
        value: "Africa/Nouakchott"
      - key: N8N_SAMESITE_COOKIE
        value: "none"
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
